#配置数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/fortress?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: eminem
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validation-query: SELECT 'X'   #验证连接
      enable: true
      #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        url-pattern: /druid/*

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
    - /toLogin*
    - /login/**
    - /resources/**
    - /static/**
    - /error/**
    - /webssh
  login-url: /toLogin
  log-out-url: /logout*
  authc-urls:
    - /**

#修改端口号为8088
server:
  port: 8080
  servlet:
    session:
      persistent: true
      timeout: 36000

# ssh log path/
ssh:
  log-path: D:/PY_Projects/SpringBootProjects/sparrow/log/audit

